//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Бипит_лаба11
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bipit_3Entities : DbContext
    {
        public Bipit_3Entities()
            : base("name=Bipit_3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arenda_book> Arenda_book { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<FIO> FIO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
